# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='ml',
            field=models.IntegerField(default=0, help_text='\u624b\u5582\u91cf(\u6beb\u5347)'),
        ),
    ]
